### ISSUE TITLE
Where to download CEDAR and Brazilian PUC-PR database

### ISSUE THREAD

**Issue by LlewynWan** [luizgh/sigver#16]
I'm working on an offline signature verification project right now. I really need those benchmark databases to compare my work on. I searched the whole Internet for CEDAR and Brazilian PUC-PR database but ended up in vain. The paper cited for CEDAR leaves no link and the email the author left was abandoned. The paper of Brazilian PUC-PR was in Portuguese and I simply don't understand a word.
Could you please share the link of these two databases. I'd be very grateful if you help me.

**Comment by luizgh** [comment]
Hello @LlewynWan . Unfortunately I cannot share the datasets directly, you need to contact the organizations that collected them. CEDAR used to be available here https://cedar.buffalo.edu/signature/, but I no longer see a download link. 

I am closing this issue since this falls out of scope of the project (also, see the disclaimer at the end of Readme.md)

**Comment by luizgh** [comment]
PS: this seems to be the link for CEDAR: http://www.cedar.buffalo.edu/NIJ/data/signatures.rar
